### PR TITLE
Fix concurrency bug in Batch Update and Delete

### PR DESCRIPTION
**Pull request by Liu79**
GetDynamicClass method: added the double check for "signature" in "classes" dictionary to avoid concurrency issues.
CreateDynamicClass: removed the upgrade to write lock because managed by the caller "GetDynamicClass" method.

Changes fixes issue #20.
Tested with 1000 concurrent updates/deletes on the same table.

### CODE REVIEW

**Comment by youngcm2** [comment]
+1

**Comment by damiangreen** [comment]
+1

**Comment by kendallmiller** [comment]
This issue has hit us as well, please merge this (or another fix) when you can.

**Comment by kendallmiller** [comment]
Thanks!

**Comment by kendallmiller** [comment]
It should be possible to close issues 149 and 161 based on this fix being merged.

**Comment by Ciprio** [comment]
When this fix will be included in your nugget (The last nugget is from january)

**Comment by pwelter34** [comment]
It has now been updated

**Comment by Ciprio** [comment]
Thanks a lot !

**Pull request merged**
